In [44]:
import warnings
warnings.simplefilter("ignore", category=UserWarning)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [45]:
from sklearn.datasets import load_digits
digits = load_digits()

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [47]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9703703703703703

In [48]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

In [49]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9814814814814815

### K Fold

In [50]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [51]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


### Get Score method

In [52]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [53]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9814814814814815

### Manual Method

In [54]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [55]:
score_lr = []
score_rf = []
score_svm = []

In [57]:
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    
    score_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))

In [58]:
score_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [59]:
score_rf

[0.9348914858096828, 0.9565943238731218, 0.9181969949916527]

In [60]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

### cross_val_score

In [61]:
from sklearn.model_selection import cross_val_score

In [65]:
lr_score = cross_val_score(LogisticRegression(), digits.data, digits.target)
lr_score

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [64]:
rf_score = cross_val_score(RandomForestClassifier(), digits.data, digits.target)
rf_score

array([0.93611111, 0.92777778, 0.96100279, 0.95264624, 0.92479109])

In [66]:
svm_score = cross_val_score(SVC(), digits.data, digits.target)
svm_score

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [71]:
lr_score.mean()

0.9137650882079852

In [72]:
rf_score.mean()

0.9404658000619005

In [73]:
svm_score.mean()

0.9632838130609718