# Indexing

In [2]:
import pandas as pd

In [3]:
n = [3,6,9,8]

In [4]:
n[0:2]

[3, 6]

In [5]:
n[-1]

8

In [6]:
n[-2]

9

In [9]:
a=np.array([3,6,9,8])

In [10]:
a[0:2]

array([3, 6])

In [11]:
a[-1]

8

In [12]:
s=np.array([[1,3,5],[2,4,6],[3,6,9]])

In [13]:
s

array([[1, 3, 5],
       [2, 4, 6],
       [3, 6, 9]])

In [15]:
s[2,1]

6

In [22]:
s[1:3,2]

array([6, 9])

In [23]:
s[1:3,1:3]

array([[4, 6],
       [6, 9]])

In [24]:
s[-1]

array([3, 6, 9])

In [25]:
s[-1,-2]

6

In [26]:
s[-2,-2]

4

In [27]:
s[-2,1:3]

array([4, 6])

In [30]:
s[0:3,1:3]

array([[3, 5],
       [4, 6],
       [6, 9]])

In [31]:
s[:,1:3]

array([[3, 5],
       [4, 6],
       [6, 9]])

In [32]:
s

array([[1, 3, 5],
       [2, 4, 6],
       [3, 6, 9]])

In [33]:
for rows in s:
    print(rows)

[1 3 5]
[2 4 6]
[3 6 9]


In [34]:
for boobs in s.flat:
    print(boobs)

1
3
5
2
4
6
3
6
9


# Stacking

In [39]:
a = np.arange(1,7).reshape(3,2)
b = np.arange(7,13).reshape(3,2)

In [40]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [43]:
np.hstack((a,b))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [44]:
np.vstack((b,a))

array([[ 7,  8],
       [ 9, 10],
       [11, 12],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6]])

In [45]:
np.hstack((b,a))

array([[ 7,  8,  1,  2],
       [ 9, 10,  3,  4],
       [11, 12,  5,  6]])

In [46]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
c = np.vstack((b,a))

In [49]:
c

array([[ 7,  8],
       [ 9, 10],
       [11, 12],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6]])

In [50]:
np.vsplit(c,2)

[array([[ 7,  8],
        [ 9, 10],
        [11, 12]]),
 array([[1, 2],
        [3, 4],
        [5, 6]])]

In [51]:
np.vsplit(c,3)

[array([[ 7,  8],
        [ 9, 10]]),
 array([[11, 12],
        [ 1,  2]]),
 array([[3, 4],
        [5, 6]])]

# Slicing

In [55]:
d = np.hstack((a,b))

In [56]:
d

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [57]:
np.hsplit(d,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [59]:
np.hsplit(d,4)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]]),
 array([[ 7],
        [ 9],
        [11]]),
 array([[ 8],
        [10],
        [12]])]

In [60]:
result = np.hsplit(d,4)

In [61]:
result

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]]),
 array([[ 7],
        [ 9],
        [11]]),
 array([[ 8],
        [10],
        [12]])]

In [62]:
result[0]

array([[1],
       [3],
       [5]])

In [63]:
result[3]

array([[ 8],
       [10],
       [12]])

# Boolean arrays

In [64]:
a = np.arange(11,100,11).reshape(3,3)

In [65]:
a

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [66]:
b = a>50

In [67]:
b

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [79]:
a[b]

array([55, 66, 77, 88, 99])

In [81]:
a[b]=0

In [82]:
a

array([[11, 22, 33],
       [44,  0,  0],
       [ 0,  0,  0]])

# Iterate numpy using nditer

In [111]:
a = np.arange(8,100,8).reshape(3,4)

In [112]:
a

array([[ 8, 16, 24, 32],
       [40, 48, 56, 64],
       [72, 80, 88, 96]])

In [113]:
for row in a:
    print(row)

[ 8 16 24 32]
[40 48 56 64]
[72 80 88 96]


In [114]:
for row in a:
    for cell in row:
        print(cell)

8
16
24
32
40
48
56
64
72
80
88
96


In [115]:
for cell in a.flatten():
    print(cell)

8
16
24
32
40
48
56
64
72
80
88
96


In [116]:
for x in np.nditer(a,order='C'):
    print(x)

8
16
24
32
40
48
56
64
72
80
88
96


In [117]:
for x in np.nditer(a,order='F'):
    print(x)

8
40
72
16
48
80
24
56
88
32
64
96


In [118]:
for x in np.nditer(a,order='F', flags=['external_loop']):
    print(x)

[ 8 40 72]
[16 48 80]
[24 56 88]
[32 64 96]


In [119]:
a

array([[ 8, 16, 24, 32],
       [40, 48, 56, 64],
       [72, 80, 88, 96]])

In [120]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*x

In [121]:
a

array([[  64,  256,  576, 1024],
       [1600, 2304, 3136, 4096],
       [5184, 6400, 7744, 9216]])

In [126]:
b = np.arange(8,25,8).reshape(3,1)

In [127]:
b

array([[ 8],
       [16],
       [24]])

In [128]:
for x,y in np.nditer([a,b]):
    print(x,y)

64 8
256 8
576 8
1024 8
1600 16
2304 16
3136 16
4096 16
5184 24
6400 24
7744 24
9216 24
