In [1]:
import numpy as np
import pandas as pd

In [2]:
revenue = np.array([[180,200,220], [24,36,40], [12,18,20]])
expenses = np.array([[80,90,100], [10,16,20],[8,10,10]])
sold_units = np.array([[30,40,50],[5,10,15],[2,5,7]])
price_per_unit = np.array([[1000,400,1200]])

## Revenue

In [3]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [4]:
columns = pd.MultiIndex.from_product([['Revenue'], ['FY 2018', 'FY 2019', 'FY 2020']])
df_revenue = pd.DataFrame(revenue, index=['iPhone', 'iPad', 'Mac'],columns=columns)
df_revenue

Revenue                
       FY 2018 FY 2019 FY 2020
iPhone     180     200     220
iPad        24      36      40
Mac         12      18      20

## Expenses

In [5]:
columns = pd.MultiIndex.from_product([['Expenses'], ['FY 2018', 'FY 2019', 'FY 2020']])
df_expenses = pd.DataFrame(expenses, index=['iPhone', 'iPad', 'Mac'],columns=columns)
df_expenses

Expenses                
        FY 2018 FY 2019 FY 2020
iPhone       80      90     100
iPad         10      16      20
Mac           8      10      10

## Profit

In [6]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [7]:
columns = pd.MultiIndex.from_product([['Profit'], ['FY 2018', 'FY 2019', 'FY 2020']])
df_profit = pd.DataFrame(profit, index=['iPhone', 'iPad', 'Mac'],columns=columns)
df_profit

Profit                
       FY 2018 FY 2019 FY 2020
iPhone     100     110     120
iPad        14      20      20
Mac          4       8      10

## Price per unit

In [8]:
df_price_per_unit = pd.DataFrame(price_per_unit, index=['Price per unit'],columns=['iPhone', 'iPad', 'Mac'])
df_price_per_unit

iPhone  iPad   Mac
Price per unit    1000   400  1200

## Sold Units

In [9]:
columns = pd.MultiIndex.from_product([['Units (Millions)'], ['FY 2018', 'FY 2019', 'FY 2020']])
df_sold_units = pd.DataFrame(sold_units, index=['iPhone', 'iPad', 'Mac'],columns=columns)
df_sold_units

Units (Millions)                
                FY 2018 FY 2019 FY 2020
iPhone               30      40      50
iPad                  5      10      15
Mac                   2       5       7

## Total Sale

In [10]:
total_sale = np.dot(price_per_unit, sold_units)
total_sale

array([[34400, 50000, 64400]])

In [11]:
columns = pd.MultiIndex.from_product([['Total Sale ($)'], ['FY 2018', 'FY 2019', 'FY 2020']])
df_total_sale = pd.DataFrame(total_sale, index=['All'],columns=columns)
df_total_sale

Total Sale ($)                
           FY 2018 FY 2019 FY 2020
All          34400   50000   64400

# <span style="color:red"> Exercise </span>

In [20]:
revenue_in_million_doller = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [21]:
columns = pd.MultiIndex.from_product([['Revenue (Million US $)'], ['FY 2018', 'FY 2019', 'FY 2020']])
df_revenue = pd.DataFrame(revenue_in_million_doller, index=['Reliance Industries','Infosys','TCS','Wipro'],columns=columns)
df_revenue

Revenue (Million US $)                
                                   FY 2018 FY 2019 FY 2020
Reliance Industries                    200     220     250
Infosys                                 68      79     105
TCS                                    110     140     180
Wipro                                   80      85      90

In [30]:
revenue_in_bdt = revenue_in_million_doller * 1000000 * 121 / 10000000
revenue_in_bdt

array([[2420. , 2662. , 3025. ],
       [ 822.8,  955.9, 1270.5],
       [1331. , 1694. , 2178. ],
       [ 968. , 1028.5, 1089. ]])

In [31]:
columns = pd.MultiIndex.from_product([['Revenue (Crore Taka)'], ['FY 2018', 'FY 2019', 'FY 2020']])
df_revenue_bdt = pd.DataFrame(revenue_in_bdt, index=['Reliance Industries','Infosys','TCS','Wipro'],columns=columns)
df_revenue_bdt

Revenue (Crore Taka)                
                                 FY 2018 FY 2019 FY 2020
Reliance Industries               2420.0  2662.0  3025.0
Infosys                            822.8   955.9  1270.5
TCS                               1331.0  1694.0  2178.0
Wipro                              968.0  1028.5  1089.0

In [33]:
sold_units = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([[20,30,15]])

In [37]:
total_sale = np.dot(price_per_unit, sold_units)
total_sale

array([[1900, 2640, 1430]])

In [39]:
df_total_sale = pd.DataFrame(total_sale, index=['Total Sale'],columns=['Jan', 'Feb', 'March'])
df_total_sale

Jan   Feb  March
Total Sale  1900  2640   1430